### ISSUE TITLE
Docker Pull not working Error: manifest

### ISSUE THREAD

**Issue by MrSiO** [LMS-Community/lms-plugin-repository#12]
Hi.
Using your provided docker-compose template we are unable to pull the :latest container image. Getting the following error message:

_ERROR: manifest for lmscommunity/logitechmediaserver:latest not found: manifest unknown_ 

Thx alot.

**Comment by michaelherger** [comment]
There's no `latest` tag. See https://hub.docker.com/repository/registry-1.docker.io/lmscommunity/logitechmediaserver/tags?page=1&ordering=last_updated for available tags.

**Comment by MrSiO** [comment]
Hi again.
I didn't put :latest in the docker-compose.yml

I used your site code as is, but when issuing the : docker-compose up -d, the error message does specify :latest

Any idea why?

Thx again

**Comment by MrSiO** [comment]
UPDATE:  Working with    __image: lmscommunity/logitechmediaserver:stable

Thx for the hint!
