### ISSUE TITLE
Warnings of deprecations in Actions

### ISSUE THREAD

**Issue by PaulWebster** [LMS-Community/lms-plugin-repository#53]
There are warnings in each run stating that some changes are required.

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/github-script, actions/checkout

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by michaelherger** [comment]
Thanks for the heads up! Yeah, I've seen this warning with almost all actions I have anywhere... It's probably time to work on this now 😀.
